#!/usr/bin/env python3
"""Repo-flow DAG guard (flow.yaml <-> tree).

Proves the documented flow against reality:
  - every top-level tracked path is claimed by exactly ONE current node (no orphans,
    no double homes); current authored/generated paths must be tracked
  - class: runtime paths must NOT be tracked; class: virtual nodes claim no paths
  - status: planned paths must NOT exist in HEAD yet (flip to current when they land)
  - class: generated nodes name a generator script that exists and a make guard target
  - edges reference declared nodes; current edges' `via` files exist
  - the automated current-edge graph is ACYCLIC — the only cycles allowed run through
    `mode: manual` edges (the owner-curation loop)
  - the mermaid DAG block in backlog/docs/FLOW.md matches the manifest (generated, drift-guarded;
    regenerate with --write-doc)

Stdlib-only (tailored line parser for flow.yaml's controlled format — no pyyaml).
Exit 0 = clean; exit 1 = drift (prints every problem).

Usage: python3 scripts/check_flow.py [--mermaid | --write-doc]
"""

import os
import re
import subprocess
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FLOW = os.path.join(REPO, "flow.yaml")
FLOW_DOC = os.path.join(REPO, "backlog", "docs", "FLOW.md")
DOC_BEGIN = "<!-- FLOW-DAG:BEGIN generated by scripts/check_flow.py --write-doc; do not hand-edit -->"
DOC_END = "<!-- FLOW-DAG:END -->"

LAYERS = {"source", "roster", "generator", "gate", "dist", "publish", "docs",
          "workbench", "runtime", "consumer"}
CLASSES = {"authored", "generated", "runtime", "virtual"}
STATUSES = {"current", "planned"}
KINDS = {"generates", "gates", "consumes", "ingests", "reports", "publishes",
         "installs", "curates"}
MODES = {"automated", "manual"}
NODE_REQUIRED = ("id", "layer", "class", "status", "paths")
EDGE_REQUIRED = ("from", "to", "kind", "mode")


def _list(v):
    v = v.strip()
    if v.startswith("[") and v.endswith("]"):
        inner = v[1:-1].strip()
        return [x.strip() for x in inner.split(",")] if inner else []
    return [v] if v else []


def _unquote(v):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "\"'":
        return v[1:-1]
    return v


def parse_flow(path):
    """Parse flow.yaml's two entry lists. Tailored to the controlled format:
    a section header at column 0 (`nodes:` / `edges:`), entries starting `  - key: v`,
    continuation keys at `    key: v`. Comments and blank lines skipped."""
    nodes, edges = [], []
    section, entry = None, None
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.rstrip("\n")
            if not line.strip() or line.lstrip().startswith("#"):
                continue
            if re.match(r"^(nodes|edges):\s*$", line):
                section = line.strip()[:-1]
                entry = None
                continue
            m = re.match(r"^  - ([a-z_]+):\s*(.*)$", line)
            if m and section:
                entry = {}
                (nodes if section == "nodes" else edges).append(entry)
                entry[m.group(1)] = m.group(2)
                continue
            m = re.match(r"^    ([a-z_]+):\s*(.*)$", line)
            if m and entry is not None:
                entry[m.group(1)] = m.group(2)
    return nodes, edges


def tracked_top_level():
    # Index, not HEAD: staged adds/moves count immediately, so the guard can run before
    # the commit that introduces them. In CI a fresh checkout's index == HEAD.
    out = subprocess.run(["git", "ls-files"],
                         cwd=REPO, capture_output=True, text=True, check=True)
    return set(p.split("/", 1)[0] for p in out.stdout.splitlines() if p)


def validate(nodes, edges, tracked):
    problems = []
    ids = {}
    for n in nodes:
        nid = n.get("id", "<missing id>")
        if nid in ids:
            problems.append(f"duplicate node id: {nid}")
        ids[nid] = n
        for k in NODE_REQUIRED:
            if k not in n:
                problems.append(f"node {nid}: missing required field `{k}`")
        if n.get("layer") not in LAYERS:
            problems.append(f"node {nid}: layer `{n.get('layer')}` not in {sorted(LAYERS)}")
        if n.get("class") not in CLASSES:
            problems.append(f"node {nid}: class `{n.get('class')}` not in {sorted(CLASSES)}")
        if n.get("status", "current") not in STATUSES:
            problems.append(f"node {nid}: status `{n.get('status')}` invalid")
        n["_paths"] = _list(n.get("paths", ""))
        if n.get("class") == "virtual" and n["_paths"]:
            problems.append(f"node {nid}: class virtual must claim no paths")
        if n.get("class") == "generated":
            gen = n.get("generator", "")
            if not gen:
                problems.append(f"node {nid}: class generated requires `generator`")
            elif n.get("status") == "current" and not os.path.exists(os.path.join(REPO, gen)):
                problems.append(f"node {nid}: generator `{gen}` does not exist")
            if not n.get("guard"):
                problems.append(f"node {nid}: class generated requires `guard` (a make target)")

    # Homing: every tracked top-level path claimed exactly once by a current node.
    claims = {}
    for n in nodes:
        if n.get("status") != "current":
            continue
        for p in n["_paths"]:
            claims.setdefault(p, []).append(n["id"])
    for p, owners in sorted(claims.items()):
        if len(owners) > 1:
            problems.append(f"path `{p}` claimed by multiple nodes: {', '.join(owners)}")
    for p in sorted(tracked):
        if p not in claims:
            problems.append(f"tracked top-level path `{p}` has NO home in flow.yaml")
    for n in nodes:
        for p in n["_paths"]:
            if n.get("status") == "planned":
                if p in tracked or os.path.exists(os.path.join(REPO, p)):
                    problems.append(
                        f"planned node {n['id']}: path `{p}` already exists — flip the node to current")
            elif n.get("class") == "runtime":
                if p in tracked:
                    problems.append(f"runtime node {n['id']}: path `{p}` must not be tracked")
            else:
                if p not in tracked:
                    problems.append(f"node {n['id']}: claimed path `{p}` is not tracked at top level")

    # Edges.
    auto = {}
    for e in edges:
        for k in EDGE_REQUIRED:
            if k not in e:
                problems.append(f"edge {e}: missing required field `{k}`")
        src, dst = e.get("from"), e.get("to")
        status = e.get("status", "current")
        if e.get("kind") not in KINDS:
            problems.append(f"edge {src}->{dst}: kind `{e.get('kind')}` not in {sorted(KINDS)}")
        if e.get("mode") not in MODES:
            problems.append(f"edge {src}->{dst}: mode `{e.get('mode')}` invalid")
        if status not in STATUSES:
            problems.append(f"edge {src}->{dst}: status `{status}` invalid")
        for endpoint in (src, dst):
            if endpoint not in ids:
                problems.append(f"edge {src}->{dst}: unknown node `{endpoint}`")
                continue
            if status == "current" and ids[endpoint].get("status") != "current":
                problems.append(f"current edge {src}->{dst}: endpoint `{endpoint}` is planned")
        via = e.get("via", "")
        if via and status == "current" and not os.path.exists(os.path.join(REPO, via)):
            problems.append(f"edge {src}->{dst}: via `{via}` does not exist")
        if status == "current" and e.get("mode") == "automated" and src in ids and dst in ids:
            auto.setdefault(src, []).append(dst)

    # Acyclicity of the automated current-edge graph (manual edges are the only
    # sanctioned way to close a loop — they run through the owner).
    WHITE, GRAY, BLACK = 0, 1, 2
    color = {nid: WHITE for nid in ids}
    def dfs(u, stack):
        color[u] = GRAY
        for v in auto.get(u, []):
            if color[v] == GRAY:
                cyc = stack[stack.index(v):] + [v] if v in stack else [u, v]
                problems.append("automated-edge CYCLE: " + " -> ".join(cyc + [v] if cyc[-1] != v else cyc))
            elif color[v] == WHITE:
                dfs(v, stack + [v])
        color[u] = BLACK
    for nid in sorted(ids):
        if color[nid] == WHITE:
            dfs(nid, [nid])

    return problems


def mermaid(nodes, edges):
    """Deterministic mermaid rendering of the manifest (house rule: no parentheses
    or special characters in node labels)."""
    order = ["roster", "source", "generator", "gate", "dist", "publish", "consumer",
             "workbench", "runtime", "docs"]
    lines = ["```mermaid", "flowchart TD"]
    key = {}
    for n in nodes:
        key[n["id"]] = "N_" + n["id"].replace("-", "_")
    for layer in order:
        members = [n for n in nodes if n.get("layer") == layer]
        if not members:
            continue
        lines.append(f"  subgraph L_{layer}[{layer}]")
        for n in members:
            label = n["id"].replace("-", " ")
            if n.get("status") == "planned":
                label += " planned"
            lines.append(f"    {key[n['id']]}[{label}]")
        lines.append("  end")
    for e in edges:
        if e.get("from") not in key or e.get("to") not in key:
            continue
        label = e.get("kind", "")
        if e.get("status", "current") == "planned":
            label += " planned"
        arrow = "-.->" if (e.get("mode") == "manual" or e.get("status") == "planned") else "-->"
        lines.append(f"  {key[e['from']]} {arrow}|{label}| {key[e['to']]}")
    planned = [key[n["id"]] for n in nodes if n.get("status") == "planned"]
    lines.append("  classDef planned stroke-dasharray: 6 4")
    if planned:
        lines.append("  class " + ",".join(planned) + " planned")
    lines.append("```")
    return "\n".join(lines)


def doc_block_check(nodes, edges, write=False):
    want = DOC_BEGIN + "\n" + mermaid(nodes, edges) + "\n" + DOC_END
    if not os.path.exists(FLOW_DOC):
        return [f"backlog/docs/FLOW.md missing (expected the generated DAG block)"]
    text = open(FLOW_DOC, encoding="utf-8").read()
    pattern = re.compile(re.escape(DOC_BEGIN) + r".*?" + re.escape(DOC_END), re.S)
    m = pattern.search(text)
    if not m:
        return ["backlog/docs/FLOW.md: FLOW-DAG markers not found"]
    if m.group(0) != want:
        if write:
            open(FLOW_DOC, "w", encoding="utf-8").write(pattern.sub(lambda _: want, text, count=1))
            return []
        return ["backlog/docs/FLOW.md: DAG block drifted from flow.yaml — run scripts/check_flow.py --write-doc"]
    return []


def main(argv):
    nodes, edges = parse_flow(FLOW)
    if "--mermaid" in argv:
        print(mermaid(nodes, edges))
        return 0
    problems = validate(nodes, edges, tracked_top_level())
    problems += doc_block_check(nodes, edges, write="--write-doc" in argv)
    if problems:
        print(f"✗ flow drift — {len(problems)} problem(s):")
        for p in problems:
            print(f"  - {p}")
        return 1
    cur = sum(1 for n in nodes if n.get("status") == "current")
    print(f"✓ flow clean — {len(nodes)} nodes ({cur} current, {len(nodes)-cur} planned), "
          f"{len(edges)} edges; every top-level path homed; automated graph acyclic; doc DAG in sync")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
