#!/usr/bin/env python3
"""gen_claude_skills.py — build a Claude Code skill laydown from primitives-core at INSTALL TIME (ADR 0017).

The marketplace bundle (`solo-skills`) is all-or-nothing: one install, every skill. A consumer
who wants three skills and no marketplace needs the other distribution shape Claude Code
already supports — plain directories under `.claude/skills/` (project) or `~/.claude/skills/`
(user). This generator builds that laydown into a consumer-chosen directory, NEVER tracked;
`scripts/install_claude_skills.sh` is the wrapper that builds to a tempdir and runs the result.

  skills/<id>/   copied verbatim from primitives-core/skills/<id>/
  install.sh     the laydown installer: --global or --project <dir>, marker-guarded
  README.md      what travels, what does not and why (every roster entry lands on one
                 side — no silent caps), and the /name vs /plugin:name namespacing

Ship set = roster `type: skill` + `targets` including claude-code + no laydown-blocking
capability in `requires` (a `hooks` primitive and an MCP server both arrive only with a
plugin install, so a bare skills copy would ship a body that cannot work).

Deterministic and stdlib-only:

  python3 scripts/gen_claude_skills.py --out DIR [--only id[,id,...]]
"""

import argparse
import os
import shutil
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "scripts"))

from check_roster import parse_roster  # noqa: E402

ROSTER = os.path.join(REPO, "primitives-core.yaml")
PLUGINS = os.path.join(REPO, "plugins")

IGNORE = shutil.ignore_patterns(".DS_Store", "__pycache__", "*.pyc")
BLOCKING = ("hooks", "local-mcp", "hosted-mcp")

NOT_A_SKILL = ("not a skill — a `.claude/skills/` laydown carries only skills; "
               "install the plugin that ships it")
NOT_TARGETED = "roster targets do not include claude-code"


def _list(entry, key):
    v = entry.get(key, "").strip()
    if v.startswith("[") and v.endswith("]"):
        return [x.strip() for x in v[1:-1].split(",") if x.strip()]
    return [v] if v else []


def carriers(sid):
    """Plugin assemblies whose skills/<sid> exists — a symlink counts (ADR 0017)."""
    if not os.path.isdir(PLUGINS):
        return []
    return sorted(p for p in os.listdir(PLUGINS)
                  if os.path.lexists(os.path.join(PLUGINS, p, "skills", sid)))


def blocked_reason(sid, caps):
    where = carriers(sid)
    via = ("carried by " + ", ".join(f"`{p}`" for p in where) if where
           else "no plugin assembly ships it today")
    return (f"requires {', '.join(caps)} — a bare skills laydown copies skill bodies only, and a "
            f"`hooks` primitive or an MCP server arrives only with a plugin install; {via}")


def classify(entries):
    """Split the roster into (shipped ids, [(id, type, reason)]). Every entry lands on one side."""
    shipped, excluded = [], []
    for e in entries:
        eid, ptype = e["id"], e["type"]
        if ptype != "skill":
            excluded.append((eid, ptype, NOT_A_SKILL))
        elif "claude-code" not in _list(e, "targets"):
            excluded.append((eid, ptype, NOT_TARGETED))
        else:
            caps = [c for c in BLOCKING if c in _list(e, "requires")]
            if caps:
                excluded.append((eid, ptype, blocked_reason(eid, caps)))
            else:
                shipped.append(eid)
    return shipped, excluded


INSTALL_SH = """#!/usr/bin/env sh
# Lay down Claude Code skills as plain directories (no marketplace).
# Generated by scripts/gen_claude_skills.py — do not hand-edit.
# usage: ./install.sh --global | --project <dir>
set -eu
USAGE="usage: install.sh --global | --project <dir>"
case "${1:-}" in
  --global) [ $# -eq 1 ] || { echo "$USAGE" >&2; exit 2; }; ROOT="$HOME/.claude/skills" ;;
  --project)
    [ $# -eq 2 ] || { echo "$USAGE" >&2; exit 2; }
    ROOT="${2:?$USAGE}/.claude/skills" ;;
  *) echo "$USAGE" >&2; exit 2 ;;
esac
HERE="$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)"
MARKER="laid down by scripts/gen_claude_skills.py"
mkdir -p "$ROOT"
n=0
for d in "$HERE"/skills/*/; do
  s="$(basename "$d")"
  t="$ROOT/$s"
  # No marker means we did not put it there: never clobber a hand-authored or foreign skill.
  if { [ -e "$t" ] || [ -L "$t" ]; } && [ ! -f "$t/.laydown" ]; then
    echo "refusing to overwrite $t — no .laydown marker (not installed by this installer)" >&2
    exit 1
  fi
  rm -rf "$t"
  cp -R "$d" "$t"
  echo "$MARKER" > "$t/.laydown"
  n=$((n + 1))
done
echo "claude skills laydown complete — $n skill(s) -> $ROOT. Restart Claude Code / start a new session to discover."
"""


def readme(shipped, excluded, entries):
    by_id = {e["id"]: e for e in entries}
    lines = [
        "# Claude Code skill laydown",
        "",
        "_Generated at install time by `scripts/gen_claude_skills.py` from `primitives-core/`",
        "(ADR 0017; never tracked). Claude Code discovers skills as plain directories, so this",
        "lane installs individual skills with **no marketplace involved** — no plugin, no",
        "`claude plugin marketplace add`._",
        "",
        "```sh",
        "./install.sh --global            # ~/.claude/skills/",
        "./install.sh --project <dir>     # <dir>/.claude/skills/",
        "```",
        "",
        f"## What travels ({len(shipped)} skills)",
        "",
        "Copied verbatim from `primitives-core/skills/<id>/`:",
        "",
    ]
    lines += [f"- `{s}`" for s in shipped]
    lines += [
        "",
        "## What does not travel (and why)",
        "",
        "| Primitive | Type | Reason |",
        "|---|---|---|",
    ]
    lines += [f"| `{eid}` | {ptype} | {reason} |" for eid, ptype, reason in sorted(excluded)]

    prereq = [(s, deps) for s in shipped
              if (deps := [r for r in _list(by_id.get(s, {}), "requires")
                           if r.startswith(("cli:", "env:"))])]
    if prereq:
        lines += [
            "",
            "## Prerequisites that do travel",
            "",
            "These skills ship complete, but assume machine state the laydown cannot install:",
            "",
            "| Skill | Needs |",
            "|---|---|",
        ]
        lines += [f"| `{s}` | {', '.join(f'`{d}`' for d in deps)} |" for s, deps in prereq]

    lines += [
        "",
        "## Namespacing",
        "",
        "A laid-down skill is invoked as `/<name>`; the same skill installed from the",
        "`dotfiles-agents` marketplace bundle is `/<plugin>:<name>`. Install both and you get two",
        "menu entries for one body. The **folder name** is what the user types — frontmatter",
        "`name` is only a display label for project/user skills.",
        "",
        "## Refreshing / uninstalling",
        "",
        "`git pull` in the clone and re-run the wrapper: it overwrites its own laydowns in place.",
        "Each directory it installs carries a `.laydown` marker file, and it refuses any directory",
        "that lacks one — so it will not delete a skill you wrote or one it never installed, and it",
        "removes nothing else. To uninstall, delete the skill directory.",
        "",
    ]
    return "\n".join(lines)


def build(out_root, entries, only=None):
    problems = []
    shipped, excluded = classify(entries)
    if only:
        reasons = {eid: reason for eid, _, reason in excluded}
        known = set(shipped)
        for sid in only:
            if sid not in known:
                problems.append(f"--only {sid}: " + reasons.get(sid, "unknown to the roster"))
        shipped = [s for s in shipped if s in set(only)]
    if problems:
        return problems

    for sid in shipped:
        src = os.path.join(REPO, "primitives-core", "skills", sid)
        shutil.copytree(src, os.path.join(out_root, "skills", sid), ignore=IGNORE)

    install = os.path.join(out_root, "install.sh")
    with open(install, "w", encoding="utf-8") as fh:
        fh.write(INSTALL_SH)
    os.chmod(install, 0o755)
    with open(os.path.join(out_root, "README.md"), "w", encoding="utf-8") as fh:
        fh.write(readme(shipped, excluded, entries))
    return problems


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--out", required=True, metavar="DIR",
        help="build the laydown into DIR (must be absent or empty — never clobbers)",
    )
    ap.add_argument(
        "--only", metavar="id[,id,...]",
        help="ship only these skill ids (an id that is not shippable is an error)",
    )
    args = ap.parse_args(argv)
    out = os.path.abspath(args.out)
    if os.path.isdir(out) and os.listdir(out):
        print(f"✗ claude skills laydown — refusing to build into non-empty dir: {out}")
        return 1
    only = [s.strip() for s in args.only.split(",") if s.strip()] if args.only else None
    entries = parse_roster(ROSTER)
    os.makedirs(out, exist_ok=True)
    problems = build(out, entries, only)
    if problems:
        print(f"✗ claude skills laydown — {len(problems)} problem(s):")
        for p in problems:
            print(f"  - {p}")
        return 1
    skills = os.path.join(out, "skills")
    n = len(os.listdir(skills)) if os.path.isdir(skills) else 0
    print(f"✓ claude skills laydown built — {out} ({n} skills + installer)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
